import assert from "node:assert/strict";
import { loadDraft, saveDraft, finishDraft } from "../frontend/src/app/platform/thread-drafts.js";
const rows = new Map();
const storage = { getItem: (key) => rows.get(key), setItem: (key, value) => rows.set(key, value), removeItem: (key) => rows.delete(key) };
const a = { body: "Primary draft", clientId: "first" }, b = { body: "Other draft", clientId: "second" };
saveDraft(storage, "a", "", a); saveDraft(storage, "b", "", b);
saveDraft(storage, "a", "reply", b);
assert.deepEqual(loadDraft(storage, "a"), a);
assert.deepEqual(loadDraft(storage, "b"), b);
assert.deepEqual(loadDraft(storage, "a", "reply"), b);
finishDraft(storage, "a", "", a);
assert.equal(loadDraft(storage, "a").body, "");
assert.deepEqual(loadDraft(storage, "b"), b);
saveDraft(storage, "a", "", { ...a, body: "Edited during request" });
finishDraft(storage, "a", "", a);
assert.equal(loadDraft(storage, "a").body, "Edited during request");
assert.notEqual(loadDraft(storage, "a").clientId, a.clientId);
storage.setItem("colorless:thread:a:", "{}");
assert.equal(loadDraft(storage, "a").body, "");
assert.ok(loadDraft(storage, "a").clientId);
const denied = { getItem() { throw Error("denied"); }, setItem() { throw Error("denied"); } };
assert.equal(loadDraft(denied, "a").body, "");
assert.doesNotThrow(() => saveDraft(denied, "a", "", a));
console.log("Threads per-identity drafts and in-flight edit preservation OK");
